"jobs":
  "push":
    "name": "Push"
    "runs-on": "ubuntu-latest"
    "steps":
    - "uses": "actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd"
    - "uses": "hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd"
    - "uses": "extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff"
    - "uses": "actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c"
      "with":
        "cache": true
        "go-version-file": "go.mod"
    - "uses": "jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2"
      "with":
        "repo": "marcbran/jpoet"
    - "name": "Set Git config"
      "run": |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
    - "env":
        "GIT_PRIVATE_KEY": "${{ secrets.GIT_PRIVATE_KEY }}"
      "name": "Push"
      "run": "just push-provider ./providers/registry.terraform.io/hashicorp/http"
    "timeout-minutes": 5
"name": "Push registry.terraform.io/hashicorp/http"
"on":
  "push":
    "branches":
    - "main"
    "paths":
    - "internal"
    - "providers/registry.terraform.io/hashicorp/http/**"
  "workflow_dispatch": {}
"permissions":
  "contents": "read"