"jobs":
  "push":
    "name": "Push"
    "runs-on": "ubuntu-latest"
    "steps":
    - "uses": "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
    - "uses": "hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd"
    - "uses": "extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff"
    - "uses": "actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5"
      "with":
        "cache": true
        "go-version-file": "go.mod"
    - "uses": "jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2"
      "with":
        "repo": "marcbran/jpoet"
    - "name": "Set Git config"
      "run": |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
    - "env":
        "GIT_PRIVATE_KEY": "${{ secrets.GIT_PRIVATE_KEY }}"
      "name": "Push"
      "run": "just push-provider ./providers/registry.terraform.io/grafana/grafana"
    "timeout-minutes": 5
"name": "Push registry.terraform.io/grafana/grafana"
"on":
  "push":
    "branches":
    - "main"
    "paths":
    - "internal"
    - "providers/registry.terraform.io/grafana/grafana/**"
  "workflow_dispatch": {}
"permissions":
  "contents": "read"