"jobs":
  "test":
    "name": "Test"
    "runs-on": "ubuntu-latest"
    "steps":
    - "uses": "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
    - "uses": "hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85"
    - "uses": "extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b"
    - "uses": "actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417"
      "with":
        "cache": true
        "go-version-file": "go.mod"
    - "uses": "jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2"
      "with":
        "repo": "marcbran/jpoet"
    - "name": "Run tests"
      "run": "just gen-provider ./providers/registry.terraform.io/integrations/github"
    "timeout-minutes": 5
"name": "Test registry.terraform.io/integrations/github"
"on":
  "pull_request":
    "paths":
    - "internal"
    - "providers/registry.terraform.io/integrations/github/**"
  "workflow_dispatch": {}
"permissions":
  "contents": "read"