"jobs":
  "test":
    "name": "Test"
    "runs-on": "ubuntu-latest"
    "steps":
    - "uses": "actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd"
    - "uses": "hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd"
    - "uses": "extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff"
    - "uses": "actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c"
      "with":
        "cache": true
        "go-version-file": "go.mod"
    - "uses": "jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2"
      "with":
        "repo": "marcbran/jpoet"
    - "name": "Run tests"
      "run": "just gen-provider ./providers/registry.terraform.io/hashicorp/assert"
    "timeout-minutes": 5
"name": "Test registry.terraform.io/hashicorp/assert"
"on":
  "pull_request":
    "paths":
    - "internal"
    - "providers/registry.terraform.io/hashicorp/assert/**"
  "workflow_dispatch": {}
"permissions":
  "contents": "read"